# dev_applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sa.dev.us-east-1.appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/akankshakothari/Argo-cd.git
        revision: HEAD
        files:
          - path: env-config/dev/*.config.json
  template:
    metadata:
      name: "sa.{{cluster.env}}.us-east-1.{{app_tags.app_name}}"
      labels:
        app: sa.dev
    spec:
      project: default
      # Ignore manual/HPAs changing replicas on Deployments
      ignoreDifferences:
        - group: "apps"
          kind: "Deployment"
          jsonPointers:
            - /spec/replicas

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true

      # Where the kustomize overlay for each app lives
      sources:
        - repoURL: https://github.com/akankshakothari/Argo-cd.git
          targetRevision: main
          # overlays/dev/us-east-1/<app>  (app from JSON)
          path: "dev/{{cluster.app}}"

      # Argo CD destination cluster & namespace (from JSON)
      destination:
        name: "{{cluster.name}}"
        namespace: "{{cluster.namespace}}"
